name = "starfish"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
iv = ">= 1.3.2 and < 2.0.0"

[dev-dependencies]
# Versions of gleeunit above 1.6.0 specify the EUnit timeout as 60 seconds, but
# this means that we can't set it higher than that so our perft tests don't work
# properly.
gleeunit = ">= 1.0.0 and < 1.6.0"
pocket_watch = ">= 1.0.0 and < 2.0.0"
